### ISSUE TITLE
Gate bot doesn't work

### ISSUE THREAD

**Issue by ryanthebotboi** [ftuyama/duel-links-bot#2]
when using Gate Duel mode, it clicks on the gate then nothing happens
![Screenshot 2020-12-03 093938](https://user-images.githubusercontent.com/75434954/101042785-8bd8e980-354b-11eb-9f41-2a46c13a5d1b.png)

**Comment by ftuyama** [comment]
Probably it's not detecting the black background from the duelist list. Are you using the right resolution?
```
          Click(727, 341)
	  Write_log("Click duel gate.")
	  Wait_pixel(626, 743, 0xFFFFFF, 10000, "Legendary Duelist list")
	  If Compare_pixel(498, 646, 0xFFFFFF) == 0 Then
		 Switch letsDuel()
			Case -1
			   Return
		 EndSwitch
	  Else
		 Write_log("Color key depleted")
		 Click(902, 372);next legendary duelist
	  EndIf
	  Sleep(200)
```

**Comment by ftuyama** [comment]
It's fully working for me now, I'm closing this issue
